name: neon_to_do_list_app
description: A modern To-Do List application built with Neon Framework.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  neon_framework:
    git:
      url: https://github.com/hamze-ibraheem/neon_custom_mobile_framework.git
      path: NeonFramework-2/neon_framework
