platform :ios, '15.0'
use_frameworks!

target 'NeonApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeonApp can be added here

  target 'NeonAppTests' do
    inherit! :search_paths
  end

  target 'NeonAppUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
